### PR TITLE
Some refactorings

### PR DESCRIPTION
**Pull request by steveklabnik**
Hey there! You said you wanted refactorings, so I spent a few minutes today and went over this. This is 99% how I'd do it.

I kept them small so you can keep what you want and throw out what you don't!

### CODE REVIEW

**Comment by davesims** [comment]
I like the fine-grained commits. New habit acquired...

**Comment by steveklabnik** [comment]
:metal:

**Comment by adambard** [comment]
@davesims You may enjoy knowing about `git add -p` if you don't already.

**Comment by adambard** [comment]
Also yeah, thanks for the pull request! Sorry I didn't thank you earlier. I'm going to call my favorite from this one the `set` function, didn't know about that.

**Comment by steveklabnik** [comment]
It is all good. That's why they're asynchronous. No skin off my back if you take your time. :)

**Comment by davesims** [comment]
@adambard Very useful, new git trick acquired...

**Pull request closed without merging**
